// // const UserProfile = require('../models/UserProfile');
// // const { fetchFreshNews } = require('./newsService');
// // const { fetchFreshBooks } = require('./bookService');
// // const { getPersonalizedJobs } = require('./jobService');
// // const { invalidatePersonalCache } = require('./cacheService');

// // /**
// //  * Re-fetch everything for a user using their CV keywords + profession.
// //  * This is triggered by the "Repersonalize" button on the profile screen.
// //  *
// //  * @param {string} userId
// //  * @param {string} profession - from JWT token
// //  */
// // async function repersonalize(userId, profession) {
// //   // Load CV profile from MongoDB
// //   const profile = await UserProfile.findOne({ userId });

// //   if (!profile || !profile.isComplete) {
// //     const err = new Error('CV profile required to repersonalize');
// //     err.status = 403;
// //     err.code = 'PROFILE_REQUIRED';
// //     throw err;
// //   }

// //   const newsKeywords = profile.keywords?.news || [];
// //   const bookKeywords = profile.keywords?.books || [];

// //   console.log(`[Repersonalize] Starting for user:${userId} (${profession})`);
// //   console.log(`[Repersonalize] News keywords: ${newsKeywords.join(', ')}`);
// //   console.log(`[Repersonalize] Book keywords: ${bookKeywords.join(', ')}`);

// //   // Invalidate existing personal caches first
// //   await invalidatePersonalCache(userId);

// //   // Re-fetch all three sequentially to avoid Gemini rate limits
// //   // News — uses profession topics + CV news keywords
// //   console.log(`[Repersonalize] Fetching news...`);
// //   await fetchFreshNews(profession, newsKeywords, userId);

// //   // Wait between Gemini calls
// //   await new Promise((r) => setTimeout(r, 10000));

// //   // Books — uses profession recommendations + CV book keywords
// //   console.log(`[Repersonalize] Fetching books...`);
// //   await fetchFreshBooks(profession, bookKeywords, userId);

// //   // Jobs — uses CV job keywords + location + preferred type (no Gemini)
// //   console.log(`[Repersonalize] Fetching jobs...`);
// //   const jobs = await getPersonalizedJobs(profile);

// //   console.log(`[Repersonalize] Done for user:${userId}`);
// //   return { success: true, jobCount: jobs.reduce((s, sec) => s + sec.jobs.length, 0) };
// // }

// // module.exports = { repersonalize };

// const UserProfile = require('../models/UserProfile');
// const { fetchFreshNewsWithTopics } = require('./newsService');
// const { fetchFreshBooks } = require('./bookService');
// const { getPersonalizedJobs } = require('./jobService');
// const { invalidatePersonalCache } = require('./cacheService');
// /**
//  * Re-fetch everything for a user using their stored CV keywords.
//  * No Gemini call needed here — keywords were already generated during CV analysis.
//  *
//  * @param {string} userId
//  * @param {string} profession
//  */
// async function repersonalize(userId, profession) {
//   const profile = await UserProfile.findOne({ userId });

//   if (!profile || !profile.isComplete) {
//     const err = new Error('CV profile required to repersonalize');
//     err.status = 403;
//     err.code = 'PROFILE_REQUIRED';
//     throw err;
//   }

//   // These were generated by Gemini during CV analysis — rich and context-aware
//   const newsTopics = profile.keywords?.news || [];
//   const bookKeywords = profile.keywords?.books || [];

//   console.log(`[Repersonalize] user:${userId} (${profession})`);
//   console.log(`[Repersonalize] ${newsTopics.length} news topics, ${bookKeywords.length} book keywords`);

//   if (newsTopics.length === 0) {
//     const err = new Error('No news keywords found in profile — please re-upload your CV');
//     err.status = 400;
//     throw err;
//   }

//   // Invalidate existing personal caches
//   await invalidatePersonalCache(userId);

//   // ── News: use stored CV topics directly — no Gemini needed ───────────────
//   // The topics are already profession + skill specific from CV analysis
//   console.log(`[Repersonalize] Fetching news with CV topics...`);
//   await fetchFreshNewsWithTopics(profession, newsTopics, userId);

//   // Wait between steps to respect Gemini rate limit
//   // (filterAndCategorizeNews inside fetchFreshNewsWithTopics uses Gemini)
//   await new Promise((r) => setTimeout(r, 10000));

//   // ── Books: use profession-based recommendations (unchanged behavior) ───────
//   // CV book keywords are passed as extra search terms for OpenLibrary/Google
//   console.log(`[Repersonalize] Fetching books...`);
//   await fetchFreshBooks(profession, bookKeywords, userId);

//   // ── Jobs: no Gemini, uses Adzuna directly with profile data ───────────────
//   console.log(`[Repersonalize] Fetching jobs...`);
//   await getPersonalizedJobs(profile, userId);

//   console.log(`[Repersonalize] Done for user:${userId}`);
//   return { success: true };
// }

// module.exports = { repersonalize };
const UserProfile = require('../models/UserProfile');
const { fetchFreshNewsWithTopics } = require('./newsService');
const { fetchFreshBooks } = require('./bookService');
const { getPersonalizedJobs } = require('./jobService');
const { invalidatePersonalCache } = require('./cacheService');

async function repersonalize(userId, profession) {
  const profile = await UserProfile.findOne({ userId });

  if (!profile || !profile.isComplete) {
    const err = new Error('CV profile required to repersonalize');
    err.status = 403;
    err.code = 'PROFILE_REQUIRED';
    throw err;
  }

  const newsTopics = profile.keywords?.news || [];
  const bookKeywords = profile.keywords?.books || [];

  console.log(`[Repersonalize] user:${userId} (${profession})`);
  console.log(`[Repersonalize] ${newsTopics.length} news topics, ${bookKeywords.length} book keywords`);

  if (newsTopics.length === 0) {
    const err = new Error('No news keywords found — please re-upload your CV');
    err.status = 400;
    throw err;
  }

  await invalidatePersonalCache(userId);

  // ── Step 1: News (uses Gemini for filterAndCategorize) ────────────────────
  console.log(`[Repersonalize] Fetching news with ${newsTopics.length} CV topics...`);
  await fetchFreshNewsWithTopics(profession, newsTopics, userId);

  // Wait for Gemini rate limit — filterAndCategorizeNews just ran (1 Gemini call)
  console.log(`[Repersonalize] Waiting 15s before books...`);
  await new Promise((r) => setTimeout(r, 15000));

  // ── Step 2: Books (uses Gemini for generateBookRecommendations) ───────────
  console.log(`[Repersonalize] Fetching books with CV keywords: ${bookKeywords.join(', ')}...`);
  await fetchFreshBooks(profession, bookKeywords, userId);

  // Wait before jobs (no Gemini but give APIs breathing room)
  await new Promise((r) => setTimeout(r, 3000));

  // ── Step 3: Jobs (no Gemini) ──────────────────────────────────────────────
  console.log(`[Repersonalize] Fetching jobs...`);
  await getPersonalizedJobs(profile, userId);

  console.log(`[Repersonalize] Done for user:${userId}`);
  return { success: true };
}

module.exports = { repersonalize };